architectury {
    common(rootProject.enabled_platforms.split(","))
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "software.bernie.geckolib:geckolib-fabric-${minecraft_version}:${geckolib_version}"

    modApi "maven.modrinth:jade:${jade_version}+fabric"
}

